spring:
  profiles:
    active:
      "dev"
  mandatory-file-encoding: UTF-8



path:
  storage: /opt/DONDE/SOFOM/CARGAS/
  bath: /opt/DONDE/shellsPLD

---
spring:
  profiles: dev
  datasource:
    url:
      jdbc:sqlserver://169.57.33.18:1435;instanceName=MSSQLS08;databaseName=FINACEN_UAT
    username:
      FINACEN_APP_UAT
    password:
      F1N4C3N_4PP

---
spring:
  profiles: uat
  datasource:
    url:
      jdbc:sqlserver://169.57.33.18:1435;instanceName=MSSQLS08;databaseName=FINACEN_UAT
    username:
      FINACEN_APP_UAT
    password:
      F1N4C3N_4PP

---
spring:
  profiles: prod
  datasource:
    url:
      jdbc:sqlserver://192.168.80.217:1433;instanceName=MSSQLS08;databaseName=BROXELAMLMELTSAN
    username:
      USRAMLMELTSAN
    password:
      USR4MLM3LT54N
